// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAapq38FT3vXG4RI-eY9V9itCfxD0lIpDU',
    appId: '1:202506720447:web:4f03dc318b609bdac5e20a',
    messagingSenderId: '202506720447',
    projectId: 'budgetapp-d2e0b',
    authDomain: 'budgetapp-d2e0b.firebaseapp.com',
    storageBucket: 'budgetapp-d2e0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNnkQgvBnFjky2Rzij3yq6OjWblbnn630',
    appId: '1:202506720447:android:c782abd4a32d27c6c5e20a',
    messagingSenderId: '202506720447',
    projectId: 'budgetapp-d2e0b',
    storageBucket: 'budgetapp-d2e0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-QyyY3SKLLlyjWNp8qKuRybop6CouxI',
    appId: '1:202506720447:ios:da852baf0bdd44b9c5e20a',
    messagingSenderId: '202506720447',
    projectId: 'budgetapp-d2e0b',
    storageBucket: 'budgetapp-d2e0b.appspot.com',
    iosBundleId: 'com.example.ikaMusaka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv-QyyY3SKLLlyjWNp8qKuRybop6CouxI',
    appId: '1:202506720447:ios:6979d8a19d4ed25dc5e20a',
    messagingSenderId: '202506720447',
    projectId: 'budgetapp-d2e0b',
    storageBucket: 'budgetapp-d2e0b.appspot.com',
    iosBundleId: 'com.example.ikaMusaka.RunnerTests',
  );
}
